services:
  - type: web
    name: api_buscador_museu
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production
    envVars:
      - key: PORT
        value: "5000"
