services:
  - type: web
    name: api_buscador_museu
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "./database.db"
      - key: PORT
        value: "5000"
