services:
  - type: web
    name: backend
    buildCommand: npm run build
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production
    envVars:
      - key: PORT
        value: "5000"
